---
sidebar: sidebar 
permalink: get-started/intro.html 
keywords: how bluexp operational resiliency works, what is operational resiliency, bluexp 
summary: 'La résilience opérationnelle de BlueXP est un service qui vous aide à analyser les alertes et les événements afin de préserver l"intégrité, la disponibilité et les performances des services et des solutions. En utilisant le service de résilience opérationnelle et ses suggestions de correction opérationnelle IT automatisées, vous pouvez implémenter les suggestions de résolution avant une panne ou une défaillance.' 
---
= Découvrez la résilience opérationnelle de BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/concepts/


[role="lead"]
La résilience opérationnelle de BlueXP est un service qui vous aide à analyser les alertes et les événements pour préserver l'état, la disponibilité et les performances des services et des solutions. En utilisant le service de résilience opérationnelle et ses suggestions automatisées de résolution des problèmes opérationnels IT, vous pouvez implémenter les suggestions de résolution avant une panne ou une défaillance.

Ce service BlueXP implémente des mesures correctives pour les clusters NetApp ONTAP basées sur les conseils de BlueXP Digital Advisor (Active IQ). Le service détecte les vulnérabilités de sécurité, telles que les problèmes de configuration du micrologiciel et du logiciel.



== Avantages de l'utilisation de la résilience opérationnelle de BlueXP

La résilience opérationnelle de BlueXP offre les avantages suivants :

* Procédures automatisées pour les corrections sur le cluster
* Vue récapitulative du tableau de bord indiquant l'état de chaque correction de risque
* Journal qui vous permet de suivre les différentes actions effectuées




== Les avantages de la résilience opérationnelle de BlueXP

Le service de résilience opérationnelle vous permet d'atteindre les objectifs suivants :

* Utilisez des workflows automatisés qui vous aident à détecter les risques qui affectent votre environnement de stockage et à prendre des mesures pour les limiter.
* Examinez les recommandations opérationnelles et agissez en conséquence, telles que les problèmes liés aux failles de sécurité.




== Le coût

NetApp ne vous facture pas pour l'utilisation du service.



== Environnements pris en charge

La résilience opérationnelle BlueXP analyse les clusters NetApp ONTAP sur site.
